window.grammarData = [
    // Übung zur 1. Lektion
    { q: "Übersetze: Vielleicht ist er schon angekommen. (nicht 'maybe' oder 'perhaps' benutzen!)", answer: ["he might have arrived", "he might have arrived."] },
    { q: "Übersetze: Darf ich hier rauchen? Nein, du darfst nicht.", answer: ["may I smoke here? No, you may not.", "may I smoke here? No, you may not"] },
    { q: "Übersetze: Ich hätte ihm vielleicht helfen können. (nicht 'maybe' oder 'perhaps' benutzen!)", answer: ["I might have been able to help him", "i might have been able to help him."] },
    { q: "You will never ... (dürfen) drive your daddy's car.", answer: ["be allowed to"] },
    { q: "You ... stay here, but you should. (Du musst nicht hier bleiben)", answer: ["don't have to", "haven't got to", "needn't"] },
    { q: "It is not that you ... (musstest) do that, you wanted to do it.", answer: ["had to"] },
    { q: "You ... (hear; du musst doch davon gehört haben) about it.", answer: ["must have heard"] },
    { q: "You ... (darfst nicht) tell anybody about our secret.", answer: ["must not", "may not", "are not allowed to"] },
    { q: "Mobile phones are ... switched off. (Handys müssen ausgeschaltet werden.)", answer: ["to be"] },
    { q: "... call her (soll ich sie anrufen?)", answer: ["shall I", "should I"] },
    { q: "If he ... not pay, I will sue him. (wenn er nicht bezahlen sollte)", answer: ["should"] },
    { q: "Where is the beer? - You are only 15, actually you are not ... drink alcohol.", answer: ["supposed to"] },
    { q: "You ... to do more with your kids. They hardly get to see you. (nicht 'should' benutzen)", answer: ["ought"] },
    { q: "She ... to have had an affair with her fitness trainer! - That's what they say, but I can't imagine it to be true.", answer: ["is said"] },
    { q: "You are ... to be back by 10 o'clock. - Sir, I will not disappoint you.", answer: ["expected", "supposed"] },
    { q: "He ... (er will nicht) to talk to me.", answer: ["does not want", "doesn't want"] },
    { q: "... you tell me more about this? (Kannst du mir nicht mehr davon erzählen?)", answer: ["can't", "cannot"] },
    { q: "He said, he ... (Er sagte, dass er nicht würde kommen können.)", answer: ["would not be able to come", "wouldn't be able to come"] },
    { q: "How ... you say this to me? (wie wagst du)", answer: ["dare"] },
    { q: "I ... (brauche) a car of my own.", answer: ["need"] },
    { q: "I ... I am the best chess player of the school. (wage zu behaupten)", answer: ["daresay", "dare say"] },
    { q: "I ... rather take a taxi. (ich würde lieber ein Taxi nehmen)", answer: ["would"] },
    { q: "When I was a child my mother ... give me a glass of milk before I went to bed. (gab mir immer ...)", answer: ["would", "used to"] },
    { q: "You ... pay this bill, it has already been paid.", answer: ["don't have to", "haven't got to", "needn't"] },
    { q: "You must not forget your passport, tomorrow you ... (wirst du ihn brauchen)", answer: ["will need it", "'ll need it"] },
    // Übung zur 2. & 3. Lektion
    { q: "I don't know ... he went away, maybe because of his mother-in-law.", answer: ["why"] },
    { q: "Is that the subject ... they chose? (das sie wählten)", answer: ["which", "that", ""] },
    { q: "I would like to know ... they were talking ... (über wen sie redeten)", answer: ["whom about", "who about", "whom ... about", "who ... about"] },
    { q: "I don't like the guy ... tried to flirt with my wife.", answer: ["who", "that"] },
    { q: "Was it the guy ... wallet was stolen?", answer: ["whose"] },
    { q: "No, it was the one ... I knocked down.", answer: ["whom", "that", "who"] },
    { q: "Well, it was an event ... I will never forget.", answer: ["which", "that"] },
    { q: "And I hope I am someone ... this miserable jerk will never forget.", answer: ["whom", "that", "who"] },
    { q: "And was it his car ... the mirror was broken off?", answer: ["of which"] },
    { q: "Who was the person ... she did it? (für den sie es getan hat)", answer: ["for whom"] },
    { q: "... can solve this problem can make a lot of money with it. (derjenige, der)", answer: ["whoever", "he who"] },
    { q: "... you want, I can get it for you. (egal was du willst ...)", answer: ["whatever"] },
    // Übung zur 4. Lektion
    { q: "He behaved in an unacceptable way, ... he?", answer: ["didn't he", "didn't"] },
    { q: "He cannot go swimming, he is not ... yet.", answer: ["able"] },
    { q: "He didn't tell you about it, ... he?", answer: ["did", "did he"] },
    { q: "He hasn't come yet, ... ?", answer: ["has", "has he"] },
    { q: "He never apologized, ... he?", answer: ["does", "did"] },
    { q: "He never plays ... (fair), he is a born cheater.", answer: ["fairly"] },
    { q: "He was punished. (just - gerechterweise)", answer: ["justly"] },
    { q: "He won't call his Mom, ...?", answer: ["will he"] },
    { q: "He went to the hospital ... pay a visit to his mother.", answer: ["to", "in order to"] },
    { q: "I have just seen ... (leave house; ich habe gerade gesehen, wie er das Haus verlassen hat.)", answer: ["him leave", "him leaving"] },
    { q: "I have to go to bed early, tomorrow I will have to ... an exam.", answer: ["take"] },
    { q: "I want ... back before 5 o'clock. (be back; ich will dass du vor 5 Uhr zurück bist)", answer: ["you to be"] },
    { q: "Just sit down, I'll ... coffee for you.", answer: ["make"] },
    { q: "She expects ... tell her the truth. (dass du ihr immer die Wahrheit sagst)", answer: ["you to"] },
    { q: "The piano has not been used for ages, I will ... (tune; ich werde es stimmen lassen)", answer: ["tune it", "have it tuned", "get it tuned"] },
    { q: "The teacher ... the pupils write an essay on Winston Churchill. (ließ sie schreiben)", answer: ["had", "made"] },
    { q: "What is he ... over there? (Was macht er da?)", answer: ["doing"] },
    { q: "You have ... three mistakes in your dictation.", answer: ["made"] },
    { q: "... (kein Wunder) he is ill, he was walking through the snow with just a shirt on.", answer: ["no wonder"] },
    { q: "... nonsense! (talk; hör auf, Unsinn zu reden)", answer: ["stop talking"] },
    { q: "After the break we will have to ... (repair; weiter reparieren) the car.", answer: ["go on repairing", "continue repairing"] },
    { q: "Both of them are o.k., you can take ... of them.", answer: ["either of", "any of", "either"] },
    { q: "Do you really insist ... (collect; dass ich einsammle) the money.", answer: ["on me collecting"] },
    { q: "Give me ... cup of coffee, please. (noch einen)", answer: ["another"] },
    { q: "He is not a murderer, he is absolutely not capable ... (kill) a person.", answer: ["of killing"] },
    { q: "I am fed up with ... (müssen) to ask for permission every time I need to make a phone call.", answer: ["having to"] },
    // Übung zur 5. & 6. Lektion
    { q: "I want ... than 2000 Euros a month, that's the absolute minimum.", answer: ["no less", "no less than"] },
    { q: "Look at this couple. Two years ago they were honeymooning and today they are getting on ...'s nerves.", answer: ["each other"] },
    { q: "The Star Trek crew is on a mission to boldly go where ... man (or woman) has ever gone before.", answer: ["no"] },
    { q: "There is ... we have to talk about.", answer: ["something"] },
    { q: "This wine is not bad, but I preferred the ... (den anderen)", answer: ["other one", "the other one"] },
    { q: "What I have to offer is ... (nichts als) blood, sweat, tears and toil.", answer: ["nothing but"] },
    { q: "You two are a bunch of idiots, ... of you will ever succeed in life.", answer: ["neither of", "neither"] },
    { q: "If I ... rich, I ... go abroad. (Wenn ich reich wäre, würde ich ins Ausland gehen.)", answer: ["were rich would", "was rich would", "were ... would", "was ... would"] },
    { q: "If I ... (know) at that time, I ... (never - trust) him.", answer: ["had known would never have trusted", "had known ... would never have trusted"] },
    { q: "... (pass) the exam, I ... (continue). (Sollte ich wirklich die Prüfung bestanden haben, mache ich weiter.)", answer: ["should I really pass will continue", "if I should really pass will continue"] },
    { q: "Will I come? - He asked ...", answer: ["whether I would come", "if I would come"] },
    { q: "I will win. - I told you I ...", answer: ["would win"] },
    { q: "... (be lazy; wäre ich nicht so faul gewesen), then I would have passed the exam.", answer: ["had I not been so lazy", "if I had not been so lazy"] },
    { q: "You talk ... (als ob du wärst) my boss.", answer: ["as if you were", "as though you were"] },
    // Übung zur Grammatik der 7. Arbeitseinheit
    { q: "... he immediately called me. (Nachdem er mich gesehen hatte, rief er mich sofort; 3 Möglichkeiten)", answer: ["after he had seen me", "having seen me", "as soon as he saw me"] },
    { q: "... his age, he is super-fit. (in Anbetracht seines Alters)", answer: ["considering"] },
    { q: "... of trouble, look over there, the junior boss is coming. (da wir von ... reden)", answer: ["speaking"] },
    { q: "Before ... you should check the letter for mistakes. (Bevor du ihn abschickst)", answer: ["sending it", "you send it"] },
    { q: "I might take this job, ... (unter der Voraussetzung, dass) I get a company car and a secretary.", answer: ["providing", "on condition that", "provided that"] },
    { q: "It's such a sultry day, let's ... ! (gehen wir schwimmen)", answer: ["go swimming"] },
    { q: "We found him ... (sleep) in the armchair, drunk and smelly.", answer: ["sleeping"] },
    { q: "Why did she ... (dye, hair), it looked so much better before.", answer: ["have her hair dyed", "dye her hair"] },
    // Übung zur Grammatik der 8. & 5. Arbeitseinheit
    { q: "Indicate the stress of the underlined words: Don't touch this 'object!", answer: ["'object"] },
    { q: "I ob'ject to this proposal.", answer: ["ob'ject"] },
    { q: "With this attitude you will never ... a good athlete.", answer: ["become"] },
    { q: "The situation is ... dangerous. (wird)", answer: ["getting", "becoming"] },
    { q: "The excursion ... into a nightmare.", answer: ["turned"] },
    { q: "Add the missing words: That's not my cup of ... (ist nicht mein Bier)", answer: ["tea"] },
    { q: "How was the party? - Nothing special, really nothing to write ... about", answer: ["home"] },
    { q: "Forget about the money you've lost, there is no use crying over ... milk", answer: ["spilled", "spilt"] },
    { q: "To kill two ... with one stone.", answer: ["birds"] },
    { q: "You cannot go to the local police with what the mayor tried to do to you. The sheriff and the mayor are hand ... with each other.", answer: ["in glove"] },
    // Übung zur Grammatik der 9. Arbeitseinheit
    { q: "I will leave. - He says ...", answer: ["he will leave"] },
    { q: "I had no idea ... (return; ob er zurückkehren würde)", answer: ["whether he would return", "if he would return"] },
    { q: "I hated it. He said ...", answer: ["he had hated it"] },
    { q: "I thought noone ... suffer like this. (sollte so leiden) That is why I gave him the injection.", answer: ["should"] },
    { q: "She came yesterday. - He said ...", answer: ["she had come the day before", "she had come the previous day"] },
    { q: "She has not yet come. He said ...", answer: ["she had not come at that time", "she hadn't come at that time"] },
    { q: "She will come tomorrow. - He said ...", answer: ["she would come the day after", "she would come the following day", "she would come the next day"] },
    { q: "Write the US spelling for 'programme'", answer: ["program"] },
    { q: "Write the UK spelling for 'glamor'", answer: ["glamour"] },
    { q: "Write the UK spelling for 'maneuver'", answer: ["manoeuvre", "manœuvre"] },
    { q: "Write the UK spelling for 'controler'", answer: ["controller"] },
    { q: "I cannot just go out like that, I have to find someone to look ... my 85-year-old mother first.", answer: ["after"] },
    { q: "They can't ... wasting money like mad. They will soon run out of it. (weiter verschwenden)", answer: ["go on", "keep on"] },
    { q: "Speak ..., for God's sake, I can't understand a word of what you are saying!", answer: ["up"] },
    { q: "Hold ... for a moment, don't disconnect the phone, I can explain everything to you!", answer: ["on"] },
    { q: "You can ring me ... any time from 8 a.m. to 5 p.m.", answer: ["up"] },
    { q: "I don't know this word, I'll have to look it ... in a dictionary.", answer: ["up"] },
    { q: "What is the US equivalent of 'lorry'?", answer: ["truck"] },
    { q: "What is the UK equivalent of 'gas' (Benzin)?", answer: ["petrol"] },
    { q: "What is the UK equivalent of 'résumé'?", answer: ["cv", "curriculum vitae"] },
    { q: "What is the UK equivalent of 'chips' (z.B. für Chio Chips)?", answer: ["crisps"] },
    { q: "What is the US equivalent of 'maize'?", answer: ["corn"] },
    // Übung zur 10. Lektion
    { q: "Let's get outside! - I would ... (lieber) to stay here.", answer: ["prefer"] },
    { q: "He ... to be there. (Er war zufällig da)", answer: ["happened"] },
    { q: "He is ... to win this match. (es ist nicht wahrscheinlich, dass er...)", answer: ["unlikely"] },
    { q: "'Chef' is another word for ...", answer: ["cook"] },
    { q: "A 'warehouse' is not a 'Warenhaus' in German, but a ...", answer: ["lagerhalle"] },
    { q: "A synonym of 'eventually' is ...", answer: ["in the end", "finally"] },
    { q: "Write 'cos' in full!", answer: ["because"] },
    { q: "Write 'doncha' in full!", answer: ["don't you", "do not you"] },
    { q: "In a gymnasium people ...", answer: ["train", "exercise"] },
    { q: "In Germany ... don't put ice in their beer. (macht man kein Eis ins Bier)", answer: ["they", "people"] },
    { q: "The money you pay every month for your appartment is called ...", answer: ["rent"] },
    { q: "This is the ... (aktuelle) champion.", answer: ["current"] },
    { q: "Why are you painting the door? - I was ... (man hat es mir gesagt)", answer: ["told so", "told to do it", "told to"] },
    // Übung zur 11. Lektion
    { q: "I am very short of funds, I would rather not buy it. (da ich ...)", answer: ["as", "since"] },
    { q: "... you know, I am no friend of long discussions. (Wie du weißt)", answer: ["as"] },
    { q: "Did you join the club, ... you were interested in the sport or was it to find victims?", answer: ["because"] },
    { q: "He didn't buy the gun ... to hunt with it, what he wanted was to shoot people.", answer: ["to", "in order to"] },
    { q: "He is a good runner, ... of his age. Imagine, he will be pensioned next year.", answer: ["in spite"] },
    { q: "He refused to accept to work in his uncle's company, ... he badly needed the money.", answer: ["although", "even though"] },
    { q: "How can I pass the exam? (work hard; indem du hart arbeitest)", answer: ["by working hard"] },
    { q: "I won't be able to join the band, ... I had to sell my guitar.", answer: ["because", "as"] },
    { q: "Just give me the manuscript ... I can judge it for myself.", answer: ["so", "so that"] },
    { q: "You cannot convince him ... at him all the time. (smile; indem du ihn ständig anlächelst).", answer: ["by smiling"] },
    { q: "... (allmählich) I start to like it.", answer: ["little by little", "gradually"] },
    { q: "... (mehrere) people got injured during the match.", answer: ["several"] },
    { q: "... he graduated, he has been insufferably arrogant.", answer: ["since"] },
    { q: "... I had known about his past, I did not want him as a neighbour anymore.", answer: ["since", "as", "because"] },
    { q: "... I was a little boy, we were so poor, I was constantly hungry.", answer: ["when"] },
    { q: "Did he lose a lot of money? - Don't worry, he's got ... of it.", answer: ["lots", "a lot"] },
    { q: "Give me a ... of your ice cream.", answer: ["bit", "little"] },
    { q: "He's got ... money than us. (mehr)", answer: ["more"] },
    { q: "He's got ... money than us. (weniger)", answer: ["less"] },
    { q: "Quit smoking, ... you won't get old. (sonst)", answer: ["otherwise", "or"] },
    { q: "They've got ... pets than anyone else. (mehr)", answer: ["more"] },
    { q: "We cannot go on ... nothing had happened.", answer: ["as if", "as though"] },
    { q: "You are ... too good (viel zu gut) for him.", answer: ["much", "way"] },
    { q: "You can have a drink ... I get a quick shower.", answer: ["while"] },
    { q: "You can practice the trumpet ... you like, but not when I am around!", answer: ["whenever", "as much as"] },
    { q: "You've got ... friends than I've got brothers. (weniger)", answer: ["fewer"] },
    // Übung zur 12. Lektion
    { q: "After a long discussion, Billy „The Hook“ Johnson was declared ... (winner) of the fight by TKO. (wurde zum Sieger erklärt)", answer: ["the winner", "to be the winner"] },
    { q: "Do you remember...? (erinnerst du dich an ihn)", answer: ["him"] },
    { q: "Don't ... (vergiss das nicht!)", answer: ["forget", "forget about it", "forget it"] },
    { q: "Don't you get angry when your pupils behave like this? No, I simply ... them in the next exam, that'll teach them a lesson.", answer: ["fail"] },
    { q: "I know they have more money and political influence than we have, but we ...smart them. (wir sind schlauer)", answer: ["outsmart"] },
    { q: "I think ..., too. (das denke ich auch)", answer: ["so"] },
    { q: "Please ... this word (erklär mir bitte das Wort hier)", answer: ["explain to me"] },
    { q: "Translate: Was bedeutet \"gag\" auf Deutsch?", answer: ["What does 'gag' mean in German?", "What does gag mean in German?"] },
    { q: "What will he do after retirement? He always wanted to be a farmer, maybe he will start ... potatoes.", answer: ["growing", "planting"] },    
    { q: "You won’t worry, … ? (nicht wahr?)", answer: ["will you", "will you?"] },
    { q: "You can play chess very well! … (Ich auch!)", answer: ["me too", "so can I"] },
    { q: "You … do that! (darfst nicht)", answer: ["may not", "must not", "aren't allowed to", "are not allowed to"] },
    { q: "When … (hast Du gesehen) the report? Oh, it was two weeks ago.", answer: ["did you see"] },
    { q: "What … the clue to this puzzle mean?", answer: ["does"] },
    { q: "We look forward to … (to meet) you soon.", answer: ["meeting"] },
    { q: "We always … (to pay) on time.", answer: ["pay", "paid"] },
    { q: "We … (to spend) a lot of time on maintenance issues since 1998.", answer: ["have been spending", "have spent"] },
    { q: "They made this ... . (selbst)", answer: ["themselves", "by themselves", "on their own"] },
    { q: "The information … (to reach) us at 8 o’clock yesterday evening.", answer: ["reached"] },
    { q: "The company … (to sell) PCs for some 12 years now.", answer: ["has been selling", "has sold"] },
    { q: "Stop … (to shout) ! It gets on my nerves!", answer: ["shouting"] },
    { q: "She … leave the company immediately! (sollen)", answer: ["should", "shall", "ought to", "is supposed to", "is expected to"] },
    { q: "Please drive … ! (vorsichtiger)", answer: ["more carefully"] },
    { q: "Our costs are higher than they … last year.", answer: ["were"] },
    { q: "Only … mistakes were made. (nur ein paar)", answer: ["a few"] },
    { q: "My brother works … tax consultant. (als)", answer: ["as a"] },
    { q: "Is this your laptop? – Yes, it is ... . (meins).", answer: ["mine"] },
    { q: "Is there …whiskey left? No, I drank the rest yesterday.", answer: ["any"] },
    { q: "If you … (to read) the report, you would have known.", answer: ["had read"] },
    { q: "I’ll have finished the project … 3 p.m. tomorrow. (bis spätestens)", answer: ["by"] },
    { q: "I sing well, but my cousin sings … . (schlecht)", answer: ["badly", "terribly"] },
    { q: "I haven’t seen the sales figures yet. I … . (Ich auch nicht)", answer: ["haven't either", "have not either", "neither have I"] },
    { q: "I expect … what I say! (dass Du machst)", answer: ["you to do"] },
    { q: "I … (to help) you, if you were a little more polite.", answer: ["would help", "would"] },
    { q: "How many pence … in a pound?", answer: ["are"] },
    { q: "He is looking forward to … (to read) the next issue.", answer: ["reading"] },
    { q: "He hugged her. She hugged him. They hugged ... . (sich umarmen)", answer: ["each other", "one another"] },
    { q: "He didn’t … to sing. (wollen)", answer: ["want", "want to"] },
    { q: "Did you hear … outside? (Jemanden)", answer: ["anybody", "somebody"] },
    { q: "All visitors … (to expect) to arrive by 8 a.m.", answer: ["are expected"] },
    { q: "All the participants … (to arrive) before the doors even opened.", answer: ["had arrived"] },
    { q: "… three months we check our accounts. (Alle drei Monate)", answer: ["every"] },
    { q: "… people live in Scotland than in England. (Weniger)", answer: ["fewer"] },
    { q: "… expects the Spanish Inquisition! (Keiner)", answer: ["nobody", "noone", "no one"] },
    { q: "… car is this? – It is in my way. (Wessen)", answer: ["whose"] },
    { q: "“I saw the film” He said he … (to see) the film.", answer: ["had seen"] },
    { q: "‘Will you see him tomorrow?’ – He asked if I … .", answer: ["would see him the day after", "would see him the following day", "would see him the next day"] },
    { q: "... can go there. (Jeder)", answer: ["everybody", "anybody"] }
];