window.abbreviationsData = [
    { q: "What is the 'D' in Washington D.C.?", options: ["District", "Department", "Division"], answer: "District" },
    { q: "The two main banking groups in the UK are Lloyds Banking Group and the ... Group.", options: ["RBS", "HSBC", "HBOS"], answer: "RBS" },
    { q: "The law that opened up the banking system in the USA after 1999 and allowed banks to offer more diverse services was called the ...", options: ["GLB Act", "GSA Act", "DFA Act"], answer: "GLB Act" },
    { q: "The ... is a market category of the LSE which lists small growing companies.", options: ["AIM", "ICE", "OTC"], answer: "AIM" },
    { q: "What is the largest stock exchange in the USA?", options: ["NYSE", "NASDAQ", "AMEX"], answer: "NYSE" },
    { q: "The ... is a network of American exchanges which started in 2000.", options: ["ISE", "ICE", "SEC"], answer: "ISE" },
    { q: "Which American stock exchange mainly lists newer, technological firms?", options: ["NASDAQ", "NYSE", "LSE"], answer: "NASDAQ" },
    { q: "In the context of insurance, OFC stands for ... Federal Charter.", options: ["Optional", "Official", "Organizational"], answer: "Optional" },
    { q: "In economic terms, what does PPP stand for?", options: ["Purchasing Power Parity", "Private Property Protection", "Public Policy Proposal"], answer: "Purchasing Power Parity" },
    { q: "What is the FTSE and what does it stand for?", options: ["Financial Times Stock Exchange", "Federal Trade Security Exchange", "Foreign Trade Standard Exchange"], answer: "Financial Times Stock Exchange" },
    { q: "A business organisation whose shares can be sold to the general public is known as a ...", options: ["PLC (Public Limited Company)", "LLC (Limited Liability Company)", "LLP (Limited Liability Partnership)"], answer: "PLC (Public Limited Company)" },
    { q: "The very first sale of a company's shares to the public is called an ...", options: ["IPO (Initial Public Offering)", "OTC (Over The Counter)", "M&A (Mergers and Acquisitions)"], answer: "IPO (Initial Public Offering)" },
    { q: "Securities traded via a broker-dealer network rather than on a centralized exchange are referred to as ...", options: ["OTC (Over The Counter)", "IPO (Initial Public Offering)", "ICE (InterContinental Exchange)"], answer: "OTC (Over The Counter)" },
    { q: "The London Stock Exchange Group is abbreviated as ...", options: ["LSEG", "LSEA", "LSEC"], answer: "LSEG" },
    { q: "The electronic quotation system used by the London Stock Exchange is known as ...", options: ["SEAQ", "NASDAQ", "ICE"], answer: "SEAQ" },
    { q: "An American Fortune 500 company that operates global exchanges and clearing houses is the ...", options: ["ICE (InterContinental Exchange)", "SEC (Securities Exchange Commission)", "FSA (Financial Services Authority)"], answer: "ICE (InterContinental Exchange)" },
    { q: "The US federal agency responsible for enforcing federal securities laws is the ...", options: ["SEC (Securities Exchange Commission)", "FSA (Financial Services Authority)", "FSOC (Financial Stability Oversight Council)"], answer: "SEC (Securities Exchange Commission)" },
    { q: "The former quasi-judicial body responsible for the regulation of the financial services industry in the UK was the ...", options: ["FSA (Financial Services Authority)", "SEC (Securities Exchange Commission)", "MPC (Monetary Policy Committee)"], answer: "FSA (Financial Services Authority)" },
    { q: "A stock market index that measures the stock performance of 30 large companies listed on stock exchanges in the US is the ...", options: ["DJIA (Dow Jones Industrial Average)", "S&P (Standard and Poors)", "FTSE (Financial Times Stock Exchange)"], answer: "DJIA (Dow Jones Industrial Average)" },
    { q: "A US stock market index based on the market capitalizations of 500 large companies is the ...", options: ["S&P (Standard and Poors)", "DJIA (Dow Jones Industrial Average)", "FTSE (Financial Times Stock Exchange)"], answer: "S&P (Standard and Poors)" },
    { q: "An insurance policy that covers professionals for claims made against them for inadequate advice is known as ...", options: ["PI (Professional Indemnity)", "BOP (Business Owner Policy)", "OFC (Optional Federal Charter)"], answer: "PI (Professional Indemnity)" },
    { q: "A package of insurance policies combined into a single contract for small and medium-sized businesses is a ...", options: ["BOP (Business Owner Policy)", "PI (Professional Indemnity)", "OFC (Optional Federal Charter)"], answer: "BOP (Business Owner Policy)" },
    { q: "The committee at the Bank of England responsible for setting interest rates is the ...", options: ["MPC (Monetary Policy Committee)", "SEC (Securities Exchange Commission)", "FSA (Financial Services Authority)"], answer: "MPC (Monetary Policy Committee)" },
    { q: "The US organization formed after the 2008 financial crisis to monitor systemic risk is the ...", options: ["FSOC (Financial Stability Oversight Council)", "SEC (Securities Exchange Commission)", "MPC (Monetary Policy Committee)"], answer: "FSOC (Financial Stability Oversight Council)" },
    { q: "The consolidation of companies or assets through various types of financial transactions is called ...", options: ["M&A (Mergers and Acquisitions)", "IPO (Initial Public Offering)", "OTC (Over The Counter)"], answer: "M&A (Mergers and Acquisitions)" }
];

window.theoryData = [
    { q: "Who was the first president of the USA?", options: ["George Washington", "Thomas Jefferson", "Abraham Lincoln"], answer: "George Washington" },
    { q: "Who controls the debates in the British House of Commons?", options: ["The Speaker", "The Prime Minister", "The Lord Chancellor"], answer: "The Speaker" },
    { q: "Which Secretary carries the highest ranking/status in the US Government?", options: ["The Secretary of State", "The Secretary of Defense", "The Secretary of the Treasury"], answer: "The Secretary of State" },
    { q: "What is the approx. population of the USA?", options: ["330-340 million", "250-260 million", "400-410 million"], answer: "330-340 million" },
    { q: "The USA is based on a ... system of rule whereby the power is shared between central government and states or local government.", options: ["Federal", "Unitary", "Confederal"], answer: "Federal" },
    { q: "The United Kingdom is made up of England, Wales, Scotland and ...", options: ["Northern Ireland", "Republic of Ireland", "Isle of Man"], answer: "Northern Ireland" },
    { q: "The two debating chambers involved in the British law-making process are the House of Commons and the ...", options: ["House of Lords", "Senate", "House of Representatives"], answer: "House of Lords" },
    { q: "The most dominant sector of the UK economy is the ... sector.", options: ["Service", "Manufacturing", "Agricultural"], answer: "Service" },
    { q: "The government has the ... function.", options: ["Executive", "Legislative", "Judicial"], answer: "Executive" },
    { q: "The diverse mixture of peoples and cultures in the USA became known as the ...", options: ["Melting Pot", "Salad Bowl", "Cultural Mosaic"], answer: "Melting Pot" },
    { q: "The Chancellor of the Exchequer is responsible for ... decisions.", options: ["Financial", "Foreign Policy", "Defense"], answer: "Financial" },
    { q: "The ... is the US chamber with 100 members each elected for 6 years.", options: ["Senate", "House of Representatives", "Supreme Court"], answer: "Senate" },
    { q: "In 1999 d... gave powers to the home nations.", options: ["Devolution", "Decentralization", "Deregulation"], answer: "Devolution" },
    { q: "For how many years was the UK in the EU (EEC/EC)?", options: ["47 years", "35 years", "52 years"], answer: "47 years" },
    { q: "Boris Johnson is the leader of which political party?", options: ["Conservative Party", "Labour Party", "Liberal Democrats"], answer: "Conservative Party" },
    { q: "Before an Act of Parliament officially completes the law-making process, the Queen signs the legislation. This is known as Royal ...", options: ["Assent", "Decree", "Proclamation"], answer: "Assent" },
    { q: "A geographical area represented by one Member of Parliament in the UK is called a ...", options: ["Constituency", "District", "County"], answer: "Constituency" },
    { q: "1776 saw the ... of Independence in the USA.", options: ["Declaration", "Constitution", "Articles"], answer: "Declaration" },
    { q: "... is the umbrella term for the two houses in US bicameral politics.", options: ["Congress", "Parliament", "Legislature"], answer: "Congress" },
    { q: "The ... sector of the UK economy covers business organisations like sole traders, partnerships, private limited companies and public limited companies.", options: ["Private", "Public", "Voluntary"], answer: "Private" },
    { q: "... banks are banks for businesses offering advice on e.g. mergers and acquisitions.", options: ["Corporate / merchant", "Retail / consumer", "Central / national"], answer: "Corporate / merchant" },
    { q: "The central bank of the USA is called the ...", options: ["Federal Reserve", "Bank of America", "National Treasury"], answer: "Federal Reserve" },
    { q: "Which organisation issues the currency in the USA?", options: ["Department of the Treasury", "Federal Reserve", "United States Mint"], answer: "Department of the Treasury" },
    { q: "The Big ... refers to the restructuring of the London Stock Exchange and its general modernisation, so called because its computer system crashed on the day it reopened.", options: ["Bang", "Crash", "Boom"], answer: "Bang" },
    { q: "What kind of shares are sold on the primary market of the LSE?", options: ["New shares (first-time sale)", "Resale shares (subsequent trading)", "Over-the-counter shares"], answer: "New shares (first-time sale)" },
    { q: "In which year did the NYSE merge with Euronext?", options: ["2007", "1999", "2012"], answer: "2007" },
    { q: "Lloyds of London is an insurance ...", options: ["market", "company", "syndicate"], answer: "market" },
    { q: "‘Names’ at Lloyds of London can now be private and corporate. Their main function is to provide ...", options: ["capital", "management", "insurance policies"], answer: "capital" },
    { q: "Corporate names have been allowed since Lloyds ... in 1996.", options: ["Renewal Plan", "Recovery Plan", "Reconstruction Plan"], answer: "Renewal Plan" },
    { q: "What do you call a group of insurance specialists in the Room at Lloyds of London?", options: ["syndicate", "committee", "cartel"], answer: "syndicate" },
    { q: "The first insurance policies compiled in the USA were for protection in the event of ...", options: ["fire", "flood", "theft"], answer: "fire" },
    { q: "Which kind of agents only represent a single insurance company and only do business with that company?", options: ["captive", "independent", "broker"], answer: "captive" },
    { q: "What is the English equivalent for 'BWL'?", options: ["Business Administration", "Economics", "Commerce"], answer: "Business Administration" },
    { q: "What is the English equivalent for 'VWL'?", options: ["Economics", "Business Administration", "Political Science"], answer: "Economics" },
    { q: "What are two English words for 'Kunde'?", options: ["customer and client", "buyer and shopper", "consumer and patron"], answer: "customer and client" },
    { q: "What defines the public sector?", options: ["Organisations run and funded by the state", "Privately owned business organisations aiming to make a profit", "Charitable organizations funded by donations"], answer: "Organisations run and funded by the state" },
    { q: "What defines the private sector?", options: ["Privately owned business organisations aiming to make a profit", "Organisations run and funded by the state", "Non-governmental organizations providing social services"], answer: "Privately owned business organisations aiming to make a profit" },
    { q: "What are four English words for 'Angebot'?", options: ["offer, quotation, bid, tender", "demand, request, order, purchase", "invoice, receipt, bill, statement"], answer: "offer, quotation, bid, tender" },
    { q: "What is the English word for 'Konkurrenzfähigkeit'?", options: ["competitiveness", "profitability", "sustainability"], answer: "competitiveness" },
    { q: "What does the primary sector refer to?", options: ["Extractive industry (getting the raw material e.g. farming, mining)", "Manufacturing and processing (changing the raw material)", "Commerce (services and aids to trade)"], answer: "Extractive industry (getting the raw material e.g. farming, mining)" },
    { q: "What does the secondary sector refer to?", options: ["Manufacturing and processing (changing the raw material e.g. purifying oil)", "Extractive industry (getting the raw material e.g. farming, mining)", "Commerce (services and aids to trade)"], answer: "Manufacturing and processing (changing the raw material e.g. purifying oil)" },
    { q: "What does the tertiary sector refer to?", options: ["Commerce (services and aids to trade e.g. transport, retail)", "Extractive industry (getting the raw material e.g. farming, mining)", "Manufacturing and processing (changing the raw material)"], answer: "Commerce (services and aids to trade e.g. transport, retail)" },
    { q: "What is the secondary market?", options: ["Refers to the resale of shares (subsequent trading)", "Refers to the sale of new shares (first-time sale)", "The market where larger companies trade securities"], answer: "Refers to the resale of shares (subsequent trading)" },
    { q: "What is the name of the market where larger, more established companies trade their securities?", options: ["Main market", "Alternative Investment Market", "OTC market"], answer: "Main market" },
    { q: "A fundamental economic concept that describes the relationship between availability and desire for a product is ... and demand.", options: ["supply", "cost", "price"], answer: "supply" },
    { q: "Innovation in business is often driven by R&D, which stands for research and ...", options: ["development", "distribution", "design"], answer: "development" },
    { q: "What is the difference between visible and invisible goods?", options: ["Tangible vs intangible (goods vs services)", "Heavy vs light", "Imported vs exported"], answer: "Tangible vs intangible (goods vs services)" },
    { q: "What is the English term for 'Devisen'?", options: ["Foreign exchange (currency)", "Stock exchange", "Domestic equity"], answer: "Foreign exchange (currency)" },
    { q: "How much of the market share constitutes a monopoly in the UK?", options: ["25%", "50%", "75%"], answer: "25%" },
    { q: "What is the English term for 'Handelsrecht'?", options: ["Commercial law", "Criminal law", "Tort law"], answer: "Commercial law" },
    { q: "What is the English term for 'Arbeitsrecht'?", options: ["Employment law", "Civil law", "Property law"], answer: "Employment law" },
    { q: "What is the English term for 'Verbraucherschutz'?", options: ["Consumer protection", "Customer service", "Client privacy"], answer: "Consumer protection" },
    { q: "What is GDP (Gross Domestic Product)?", options: ["The value of all goods produced within a country in a time period", "GDP plus payments from citizens abroad", "The purchasing power parity of a nation"], answer: "The value of all goods produced within a country in a time period" },
    { q: "What is GNP (Gross National Product)?", options: ["GDP plus the value of payments coming into a country from its citizens abroad", "The value of all goods produced within a country", "The measure of a country's national debt"], answer: "GDP plus the value of payments coming into a country from its citizens abroad" },
    { q: "Where and when did the London Stock Exchange (LSE) originate?", options: ["London, coffee house, 1698", "London, parliament, 1750", "London, royal exchange, 1801"], answer: "London, coffee house, 1698" },
    { q: "Which stock exchange has frequently tried to acquire the LSEG over the last 10 years?", options: ["NASDAQ", "NYSE", "Nikkei"], answer: "NASDAQ" },
    { q: "What is the AIM and when was it launched?", options: ["Alternative Investment Market, started in 1995 for smaller growing companies", "American Investment Market, started in 2000 for tech companies", "Asian Investment Market, started in 1990 for foreign shares"], answer: "Alternative Investment Market, started in 1995 for smaller growing companies" },
    { q: "What is techMark?", options: ["A market listing companies in the technical or medical field", "A market for agricultural companies", "A market for regional companies"], answer: "A market listing companies in the technical or medical field" },
    { q: "What is landMARK?", options: ["A market listing companies according to location (region)", "A market for foreign tech companies", "A real estate trading platform"], answer: "A market listing companies according to location (region)" },
    { q: "What was the Buttonwood Agreement?", options: ["The start of the NYSE, brokers and merchants sat under a buttonwood tree", "An agreement to merge the LSE and NASDAQ", "The founding charter of the Federal Reserve"], answer: "The start of the NYSE, brokers and merchants sat under a buttonwood tree" },
    { q: "Which architect designed the Stock Exchange building at 18 Broad Street?", options: ["George B Post", "Christopher Wren", "Frank Lloyd Wright"], answer: "George B Post" },
    { q: "As of September 2012, what was the value of stocks listed on the NYSE compared to NASDAQ?", options: ["NYSE is 3x more value than NASDAQ", "NASDAQ is 3x more value than NYSE", "They are equal in value"], answer: "NYSE is 3x more value than NASDAQ" },
    { q: "Which sort of companies are typically listed on the NYSE vs NASDAQ?", options: ["NYSE: older, more established; NASDAQ: newer, more tech-based", "NYSE: newer, tech-based; NASDAQ: older, established", "Both list identical types of companies"], answer: "NYSE: older, more established; NASDAQ: newer, more tech-based" },
    { q: "Name two different types of trading securities.", options: ["OTC (over the counter) and Listed companies", "Primary and Secondary", "Public and Private"], answer: "OTC (over the counter) and Listed companies" },
    { q: "What is the Fortune 500?", options: ["The 500 largest companies trading in the USA on a given day", "The 500 most profitable banks in the world", "The top 500 European companies"], answer: "The 500 largest companies trading in the USA on a given day" },
    { q: "What is the S&P 500?", options: ["500 companies selected by Standard and Poors", "The 500 oldest companies in the US", "500 randomly selected tech companies"], answer: "500 companies selected by Standard and Poors" },
    { q: "In insurance terminology, what is a synonym for 'agent'?", options: ["Representative", "Underwriter", "Pool"], answer: "Representative" },
    { q: "In insurance terminology, what is a synonym for 'compensation'?", options: ["Indemnity", "Premium", "Contribution"], answer: "Indemnity" },
    { q: "In insurance terminology, what is a synonym for 'peril'?", options: ["Risk", "Fund", "Policy"], answer: "Risk" },
    { q: "In insurance terminology, what is a synonym for 'premium'?", options: ["Contribution", "Indemnity", "Representative"], answer: "Contribution" },
    { q: "In insurance terminology, what is a synonym for 'fund'?", options: ["Pool", "Risk", "Contract"], answer: "Pool" },
    { q: "In insurance terminology, what is a synonym for 'insurer'?", options: ["Underwriter", "Policy holder", "Agent"], answer: "Underwriter" },
    { q: "In insurance terminology, what is a synonym for 'policy'?", options: ["Contract", "Pool", "Price-setting"], answer: "Contract" },
    { q: "When did Lloyd's of London start?", options: ["1774 (end of 18th century)", "1850", "1901"], answer: "1774 (end of 18th century)" },
    { q: "What is a person of the syndicate authorised to sign for the syndicate and accept risk called?", options: ["Underwriter", "Managing agent", "Coverholder"], answer: "Underwriter" },
    { q: "What is the company that runs a syndicate at Lloyd's called?", options: ["Managing agent", "Capital provider", "Local representative"], answer: "Managing agent" },
    { q: "Why are coverholders important for Lloyd's?", options: ["They provide local knowledge in international locations", "They manage the central IT systems", "They handle marketing in London"], answer: "They provide local knowledge in international locations" },
    { q: "What are some different areas of specialisation in insurance at Lloyd's?", options: ["Marine, aviation, art, kidnap and ransom", "Only vehicle and property", "Only health and life insurance"], answer: "Marine, aviation, art, kidnap and ransom" },
    { q: "Where is the insurance business conducted at Lloyd's?", options: ["The Room", "The Floor", "The Pit"], answer: "The Room" },
    { q: "Who founded the Philadelphia Contributionship for the Insurance of Houses from Loss by Fire?", options: ["Benjamin Franklin", "George Washington", "Thomas Jefferson"], answer: "Benjamin Franklin" },
    { q: "Name the two aspects of insurance covered in a typical policy.", options: ["Property and liability", "Life and health", "Auto and marine"], answer: "Property and liability" },
    { q: "What is the London Bullion Market?", options: ["An international market for gold, silver and precious metals", "A market for agricultural goods", "A stock exchange for mining companies"], answer: "An international market for gold, silver and precious metals" },
    { q: "What is the Baltic Exchange?", options: ["A market for goods (cargo) and ships (vessels)", "A foreign exchange market", "An insurance syndicate"], answer: "A market for goods (cargo) and ships (vessels)" },
    { q: "When was the central bank of the UK founded?", options: ["1694", "1801", "1914"], answer: "1694" },
    { q: "Which institution issues banknotes in the UK?", options: ["Bank of England and Bank of Scotland", "Royal Mint", "Lloyds Bank"], answer: "Bank of England and Bank of Scotland" },
    { q: "What is the currency in the UK?", options: ["Pound Sterling", "Euro", "Dollar"], answer: "Pound Sterling" },
    { q: "When did the Docklands area begin to develop and why is it important?", options: ["1980s, for international banks", "1950s, for manufacturing", "1990s, for tech startups"], answer: "1980s, for international banks" },
    { q: "What are alternative names for retail banks?", options: ["High-street banks", "Merchant banks", "Central banks"], answer: "High-street banks" },
    { q: "Which banks are known as the Big Four in the UK?", options: ["Barclays, HSBC, Lloyds, RBS", "Barclays, Santander, HSBC, Halifax", "Lloyds, RBS, NatWest, Standard Chartered"], answer: "Barclays, HSBC, Lloyds, RBS" },
    { q: "What was the biggest development in the UK banking system in the 21st century?", options: ["Banking Reform 2014", "Big Bang 1986", "Gramm-Leach-Bliley Act 1999"], answer: "Banking Reform 2014" },
    { q: "What services do modern merchant banks offer?", options: ["Corporate advice, portfolio management, investments", "Consumer loans and mortgages", "Issuing national currency"], answer: "Corporate advice, portfolio management, investments" },
    { q: "In which buildings is US currency created?", options: ["Bureau of the Mint, Bureau of Engraving and Printing", "Federal Reserve Banks", "Wall Street Vaults"], answer: "Bureau of the Mint, Bureau of Engraving and Printing" },
    { q: "What is the US 5 cent coin commonly known as?", options: ["Nickel", "Dime", "Quarter"], answer: "Nickel" },
    { q: "Which act prohibited any institution from combining investment banking, commercial banking, or insurance?", options: ["Glass-Steagall Act", "Dodd-Frank Act", "Volcker Rule"], answer: "Glass-Steagall Act" },
    { q: "Name two benefits of the Gramm-Leach-Bliley Act (GLBA).", options: ["More scope to offer insurance, real-estate, investment and interstate banking", "Stricter consumer protection and higher taxes", "It created the Federal Reserve System"], answer: "More scope to offer insurance, real-estate, investment and interstate banking" },
    { q: "What was the main aim of the Dodd-Frank Act?", options: ["To stop banks getting too powerful and protect consumers (2010)", "To deregulate the banking sector (1999)", "To introduce the gold standard"], answer: "To stop banks getting too powerful and protect consumers (2010)" },
    { q: "What does the FSOC have the authority to do?", options: ["Break up large banks", "Issue national currency", "Set federal interest rates"], answer: "Break up large banks" },
    { q: "What is the Volcker Rule?", options: ["Restricts investment by banks", "Allows unlimited trading", "Merges commercial banks"], answer: "Restricts investment by banks" }
];